import ServerUserInfo from "@/components/ServerUserInfo";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={`${inter.className} flex flex-col`}>
          <header className="p-4 flex flex-1">
            <h2>
              <Link href="/">Uplift Procure</Link>
            </h2>
            <nav>
              <Link href="/vendors">Vendors</Link>
            </nav>
            <div className="flex flex-1 justify-end">
              <a href="/api/auth/login">Log in</a>
              <a href="/api/auth/logout">Log out</a>
              <ServerUserInfo />
            </div>
          </header>
          <main className="p-4">{children}</main>
        </body>
      </UserProvider>
    </html>
  );
}
